# Generated by Django 4.1.7 on 2023-04-20 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_remove_reservation_user_apartment_agent_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apartment',
            old_name='adresse',
            new_name='address',
        ),
    ]
