# Generated by Django 4.1.7 on 2023-04-24 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0004_rename_adresse_apartment_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
