# Generated by Django 4.1.7 on 2023-04-29 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0005_alter_reservation_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='image',
        ),
    ]
