# Generated by Django 4.1.7 on 2023-04-20 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_agent_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='slug',
            field=models.CharField(max_length=255),
        ),
    ]
